language: php

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    include:
        # Symfony 4
        - php: 7.1
        - php: 7.2
        - php: 7.3
        # Symfony LTS
        - php: 7.3
          env: DEPENDENCIES="symfony/lts:^3"
        # development dependencies
        - php: 7.3
          env: STABILITY="dev"
    fast_finish: true

allow_failures:
    # Dev-master is allowed to fail.
    - env: STABILITY="dev"

before_install:
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
    - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; echo ${DEPENDENCIES}; fi;

install: composer update --prefer-dist

script:
    - vendor/bin/phpunit
